CREATE TABLE igbot.task_log (
    id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    account VARCHAR(36) NOT NULL DEFAULT '',
    type VARCHAR(36) NOT NULL DEFAULT '',
    details VARCHAR(36) NOT NULL DEFAULT '',
    datetime DATETIME NOT NULL DEFAULT NOW()
);